---
driver:
  name: ec2
  region: ca-central-1
  security_group_ids: sg-5e24cc36
  aws_ssh_key_id: 25apr2017
  block_device_mappings:
    - device_name: /dev/sda1
      ebs:
        delete_on_termination: true
  # network:
  #   - ["private_network", { type: "dhcp"}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  # - name: rhel-7
  # - name: ubuntu-16.04
  # - name: centos-7

transport:
  ssh_key: ~/.ssh/25apr2017.pem

suites:
  - name: default
    run_list:
      - recipe[jenkins::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
