sudo: required
services:
  - docker
language: ruby
before_install:
  - curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -c current -P chefdk
script:
  - /opt/chefdk/bin/chef exec foodcritic .
  - export KITCHEN_YAML=.kitchen.dokken.yml
  - /opt/chefdk/bin/chef exec kitchen test -d never
